site_name: nashme.sh

# Navigation
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - MQTT: mqtt.md
  - Infrastructure Nodes: resources/infrastructure-nodes.md
  - High SNR Connections: resources/connections.md
  - Fundraising: https://www.paypal.com/pool/9lX5JfAFdw?sr=wccr
  - Affiliate Links: resources/affiliate.md
  - Discord: https://discord.gg/sSS8gEpuh8

# Theming
theme:
  name: simple-blog
  logo: static/images/logo.png
  sidebar: true
  navigation_depth: 2
  theme_style: dark
  highlightjs: true
  components:
    site_name: true
    title: false
    menu: true
    preview: true
    footer: true
  colors:
    text: black
    title: black
    primary: black
    background: white

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
# Plugins
plugins:
  - search
  - macros


# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - static/styles/leaflet.css
  - static/styles/extra.css

extra_javascript:
  - static/js/custom.js
  - static/js/malla.js
  - static/js/leaflet.js
  - static/js/heatmap.js
  - static/js/leaflet-heatmap.js

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/sSS8gEpuh8
      name: Join our Discord
